### ISSUE TITLE
System.MissingMethodException when Microsoft.EntityFrameworkCore.Sqlite is present.

### ISSUE THREAD

**Issue by Bpflugrad** [vitalybibikov/azure-functions-extensions-swashbuckle#11]
Hello,

Sorry to write you but I'm at a loss.  I've spent the last couple days trying to upgrade one of my major projects to Functions V3.  One of my requirements is that I provide a Swagger definition for the API to facilitate remote collaboration with our front end team.  Long story short I came to your package when  this caused `AzureFunctions.Extensions.Swashbuckle 1.4.4` to stop working.

The project compiled successfully, but when executing throws `System.MissingMethodException` at `AddSwashBuckle(Assembly.GetExecutingAssembly())`.  I systematically removed things until I found that my EntityFrameworkCore database contexts were causing the issue.  I further removed things until I found that `Microsoft.EntityFrameworkCore.Sqlite 3.1.3` (also tried the 5.0.0 prerelease) being present causes the problem, even if it is not referenced.  Sqlite is part of all of my database contexts to facilitate unit testing.

I've created a minimal repro solution [here](https://github.com/Bpflugrad/AzureExtensions.Swashbuckle.MissingMethodExample).  Hopefully it will exhibit the problem.
Any ideas would be appreciated.

Here's some information about my environment too:
```
Azure Functions Core Tools (3.0.2245 Commit hash: 1d094e2f3ef79b9a478a1621ea7ec3f93ac1910d)
Function Runtime Version: 3.0.13139.0
DotNet --version 3.1.200
```

Thanks.

**Comment by vitalybibikov** [comment]
Hi, @Bpflugrad 

Thanks for the repro.

The only solution I can suggest at the moment is to downgrade to:

`    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.0" />`

As **3.1.0** references  `System.Text.Json 4.7.0`, 
while **3.1.3** references `System.Text.Json 4.7.1`, 

The later is currently not supported, as it contains several issues.

**Comment by Bpflugrad** [comment]
Wow thanks for the quick reply.  This does fix the issue.  I'm going to force all my 3.1.x libraries to 3.1.0 as I'm finding some conflicts elsewhere too.

Thanks again!
