### ISSUE TITLE
There is no documentation to help in migrating to latest version with breaking changes

### ISSUE THREAD

**Issue by DarinMacRae** [vitalybibikov/azure-functions-extensions-swashbuckle#13]
First, thank you very much for taking over this project. It was disappointing to see that the original not work with Core v3. 

Can you please document how someone might migrate from the previous version to the latest one due to the breaking changes introduced?

I updated today and I read the release notes and I see the comment about breaking changes
> Option and DocumentOption renamed to SwaggerDocOptions and SwaggerDocument 

However, I don't have any references to these types in my projects and hunting down what changed by reading your commits is taking a lot of time. I upgraded and although it compiles the result is a 500 error.

The error is that it cannot find a document. Something like "the document "v1.0" cannot be found". 

Although the default document name is called "v1" I was using "v1.0" which is working fine in the previous version but not in the the latest. (I assume this was due to changes in this library but if this was due to changes in some upstream library I apologize. Although I'd still like to know. :) )

I *do* have this document name configured in my hosts file (as per prior to the upgrade from the v1 version of this project to this v3 version).

```    "Swashbuckle": {
      "Documents": [
        {
          "Name": "v1.0",
          "Title": "Some API",
          "Version": "1.0.0"
        }
      ]
    }
```
Am I supposed to have to change this configuration now and if so to what?

The documentation doesn't provide examples that show how to use this configuration with your new version of the library so I can't compare in order to see what is different. Would you add some examples or explain how to accomplish this using a technique that would identify this breaking change?

**Comment by vitalybibikov** [comment]
Hi @DarinMacRae 

There is a full-fledged example in this repository.

This configuration you are looking for is placed in a Startup =>

https://github.com/vitalybibikov/azure-functions-extensions-swashbuckle/blob/master/src/AzureFunctions.Extensions.Swashbuckle/TestFunction/SwashBuckleStartup.cs


if you want to configure settings, then you need to use your local.settings.json file (locally)

Or AppSettings (in cloud) 

As this is a common way of handling all the configurations starting from v2

**Comment by DarinMacRae** [comment]
Thank you for the detailed explanation and help with the migration. I have moved the configuration to the Startup class and all is working well with the latest version. Your time and effort on this project is much appreciated.
