### ISSUE TITLE
Optional route parameter constraint

### ISSUE THREAD

**Issue by ducman** [vitalybibikov/azure-functions-extensions-swashbuckle#14]
I am unsure if this is supported or I'm missing some configuration to have it working. Below is an example of my route:

```cs
[HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "v1/product/search/{productNumber:int}/{productVersion:int?}")] HttpRequest request,
```

Notice the `?` which indicates that the parameter is optional. Below is what swagger generate:

![productsearchbynumber](https://user-images.githubusercontent.com/6187148/82575900-ed041700-9b3d-11ea-8df5-3c02d85cb596.png)

It seems to not end the trailing `}` in the title and it shows that the `productVersion` parameter is required when really it's optional.

I am using version 3.1.6.

**Comment by vitalybibikov** [comment]
Hi, @ducman 

Unfortunately, it does not supported.

> If the parameter is in "path", this property is required and its value MUST be true.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-7

Similar issue => 
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/406
