### ISSUE TITLE
Eample of Data For Schema

### ISSUE THREAD

**Issue by bbakermmc** [vitalybibikov/azure-functions-extensions-swashbuckle#16]
Is there an example I missed where we can setup sample/example data for what shows in the schema etc?

**Comment by vitalybibikov** [comment]
You can run this example

https://github.com/vitalybibikov/azure-functions-extensions-swashbuckle/tree/master/src/AzureFunctions.Extensions.Swashbuckle/TestFunction

**Comment by bbakermmc** [comment]
I assume I need to do this:
https://mattfrear.com/2016/01/25/generating-swagger-example-requests-with-swashbuckle/

**Comment by vitalybibikov** [comment]
There is a description of the process on the main page of a repo.

All the examples are available in the repo, you can run it to test it.

![image](https://user-images.githubusercontent.com/7008739/82752903-0c16d900-9dca-11ea-918c-7d1dbe359c34.png)


![image](https://user-images.githubusercontent.com/7008739/82752818-695e5a80-9dc9-11ea-9834-829be07dd54b.png)

![image](https://user-images.githubusercontent.com/7008739/82752822-6fecd200-9dc9-11ea-9fcd-8695752155e2.png)


Also, you need to annotate your models as it is done in repo (TestModel)

Or here

![image](https://user-images.githubusercontent.com/7008739/82752965-88a9b780-9dca-11ea-90c6-c557f0edb777.png)

**Comment by vitalybibikov** [comment]
@bbakermmc if I have anwered, please close the issue. Thanks
