### ISSUE TITLE
Configuration in host.json gets ignored

### ISSUE THREAD

**Issue by SherwoodCH** [vitalybibikov/azure-functions-extensions-swashbuckle#7]
I have added the Swashbuckle Extension (v.3.0.0) via Startup (IWebJobsStartup) but it completely ignores configurations made in host.json. Even if I change title or spec version in host.json, the default values still apply. 

My host.json 
```json
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingExcludedTypes": "Request",
            "samplingSettings": {
                "isEnabled": true
            }
        }
    },
    "extensions": {
        "Swashbuckle": {
            "Title": "Test API",
            "SpecVersion ": "2.0"
        } 
    }
}
```

My startup code: 
```csharp 
[assembly: FunctionsStartup(typeof(Startup))]
namespace namespace
{
    internal class Startup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {
            builder.AddSwashBuckle(Assembly.GetExecutingAssembly());
        }
    }
...
```

**Comment by vitalybibikov** [comment]
Hi @SherwoodCH,

All function app configuration options are managed in your app settings (for deployed apps) or your local.settings.json file (for local development).

host.json is not for config Azure function appsettings.

**Comment by SherwoodCH** [comment]
Okay, but what is the proper naming for the configs in the appsetting to configure the swagger document (title, version, description, etc)?

**Comment by bbakermmc** [comment]
@vitalybibikov What would the proper way be to do this then?  Im confused as well some things you need to configure in the host.json 

EX: This is what one of my current function apps look like and the configs seem to be working fine...

```json
{
    "version": "2.0",
    "functionTimeout": "05:00:00",
    "extensions": {
        "queues": {
            "maxDequeueCount": 5
        },
        "Swashbuckle": {
            "AddCodeParameter": false,
            "PrependOperationWithRoutePrefix": false
        }
    },
    "logging": {
        "applicationInsights": {
            "samplingExcludedTypes": "Request",
            "samplingSettings": {
                "isEnabled": true
            }
        }
    }
}
```

**Comment by abmang** [comment]
@bbakermmc take a look at this example on how you can configure the swagger in your startup:

https://github.com/vitalybibikov/azure-functions-extensions-swashbuckle/blob/master/src/AzureFunctions.Extensions.Swashbuckle/TestFunction/SwashBuckleStartup.cs

**Comment by mligtenberg** [comment]
@bbakermmc in azure functions v2 this was indeed the way to do it. Via the host.json. But as of V3 the configuration of extensions has moved to the settings.json.
