### ISSUE TITLE
QueryStringParameter with Required = true will incorrectly state that value needs to be supplied

### ISSUE THREAD

**Issue by pettermo** [vitalybibikov/azure-functions-extensions-swashbuckle#8]
On my API method I've defined the following Attribute:
[QueryStringParameter("ProjectId", "Project ID to download the Yard quote template for", DataType = typeof(int), Required = true)]        

When trying the generated /swagger/ui for the function, it will complain about missing value provided when trying to execute it - even if provided. (Required field is not provided)

![error](https://user-images.githubusercontent.com/5196350/79987335-8db6d680-84ad-11ea-9c4f-a299d34ec900.png)

Full method declaration here:

![method](https://user-images.githubusercontent.com/5196350/79987406-a7581e00-84ad-11ea-873f-54a642a0d1ee.PNG)

**Comment by vitalybibikov** [comment]
I have released 3.1.4-beta Nuget package that should fix the issue with all numeric/integer/boolean types.

Please, check it out.

https://github.com/vitalybibikov/azure-functions-extensions-swashbuckle/tree/dev

**Comment by pettermo** [comment]
Hi @vitalybibikov,

thanks for looking into my bug report. I've tested 3.1.4-Beta (up from 3.1.2-Beta), however when going to the /api/swagger/ui link, I now get this error. (No other change).
![swaggerUiIssue](https://user-images.githubusercontent.com/5196350/80870100-945efe00-8ca4-11ea-9ea8-4dc54e5d66f3.PNG)


Note: the api/swagger/json seems to work. UI fails on both Edge and Chrome (same error). I notice a // in the error URL, not sure if that is the cause or not.

**Comment by vitalybibikov** [comment]
@pettermo 
Yep, thanks for finding it, fixed in 3.1.5-beta

**Comment by pettermo** [comment]
Tried it out, and the original issue and follow up issue seems resolved! Great stuff.
