### ISSUE TITLE
Invalid swagger json generated if QueryStringParameter data type used <> string 

### ISSUE THREAD

**Issue by abmang** [vitalybibikov/azure-functions-extensions-swashbuckle#9]
If QueryStringParameter is used with data type = int, the generated swagger json is invalid because the type name that is used in the json is the fully-qualified name of int in C#, which is "System.Int32". The correct value should be "integer". I assume this is wrong for all data types other than string.

I am using OpenApi version = 2

![image](https://user-images.githubusercontent.com/64411875/80366699-f9bc8480-8889-11ea-9d25-1bfd0d4120b0.png)

![image](https://user-images.githubusercontent.com/64411875/80366747-0fca4500-888a-11ea-9385-7fb5d4d7ba4e.png)

**Comment by vitalybibikov** [comment]
Hi @abmang 

Thanks for the issue.

I have released 3.1.4-beta Nuget package that should fix it.
Please, check it out.

https://github.com/vitalybibikov/azure-functions-extensions-swashbuckle/tree/dev

**Comment by abmang** [comment]
Hi @vitalybibikov, thank you so much for the new release. will check it ou!
